# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd0069e8f34c6ceaf9aa3c8ea79904cfe245c2bbaa1d50aed8b4c03a545fead615a9e8c082932d375db98cb01a4d34504c7ef368fb46c0a65da28c5b3758c89c

test:
  secret_key_base: ad28c96f83a0c6ad66b6dee52ced491156707fd181ff4faac4ae9aa043a061bfb7f87ff5f4cbf17de55205947d785075ddc6f47133137131ded975aa65a913e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
